//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalyticsSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int idCart { get; set; }
        public Nullable<int> idOrder { get; set; }
        public Nullable<int> idMetric { get; set; }
        public string TotalPrice { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual SystemMetrics SystemMetrics { get; set; }
    }
}
