//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalyticsSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItems
    {
        public int idCartItem { get; set; }
        public Nullable<int> idCart { get; set; }
        public Nullable<int> idMetric { get; set; }
        public string MetricName { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual SystemMetrics SystemMetrics { get; set; }
    }
}
