//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalyticsSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetricHistory
    {
        public int idMetricHistory { get; set; }
        public Nullable<int> idMetric { get; set; }
        public string MetricValue { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual SystemMetrics SystemMetrics { get; set; }
    }
}
