//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalyticsSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetails
    {
        public int idPaymentDetail { get; set; }
        public Nullable<int> idOrder { get; set; }
        public string PaymentMethod { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
