//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalyticsSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int idReport { get; set; }
        public string ReportName { get; set; }
        public int TemplateId { get; set; }
        public System.DateTime GeneratedDate { get; set; }
        public string ReportData { get; set; }
    
        public virtual ReportTemplates ReportTemplates { get; set; }
    }
}
