//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalyticsSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskHistory
    {
        public int idHistory { get; set; }
        public int TaskId { get; set; }
        public int StatusId { get; set; }
        public System.DateTime ChangeDate { get; set; }
    
        public virtual TaskStatus TaskStatus { get; set; }
        public virtual Tasks Tasks { get; set; }
    }
}
