//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalyticsSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDevices
    {
        public int idUserDevice { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> idDevice { get; set; }
        public string DeviceAlias { get; set; }
    
        public virtual Devices Devices { get; set; }
        public virtual Users Users { get; set; }
    }
}
