//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalyticsSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotifications
    {
        public int idUserNotification { get; set; }
        public int UserId { get; set; }
        public int NotificationId { get; set; }
        public Nullable<bool> IsRead { get; set; }
    
        public virtual Notifications Notifications { get; set; }
        public virtual Users Users { get; set; }
    }
}
